apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "8908099"
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-web-mybob1221 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/claranet/terraform-azurerm-vnet
    title: 'Virtual Network Terraform Module'
    icon: github
  tags:
    - azure
    - vnet
    - terraform
    - high-criticality
    - ticket-number-8908099
    - entity-us
    - owner-bob-tayara
    - stack-mybob1221
    - env-prod
    - created-on-2024-07-29
  title: 'Brand New Stack mybob1221 - Azure Reource Group and Virtal Network - Ticket #8908099' # you can give any title
  description: |
   Create **Azure Virtual Network** in stack **mybob1221** and in **prod** environment\
   \
   **Ticket number:**  8908099\
   **Created on:**  2024-07-29\
   **Details:**  Create an **Azure Virtual network** and a **resource group** in a brand new stack **mybob1221**, in **prod** environment and in **us-east** region\
   **Action:**  Create a new **Resource Group** and a new **Virtual Network**\
   **Brand new stack created?:**  Yes\
   **Azure region:**  us-east\
   **Virtual network address space:**  10.30.0.0/16\
   **Virtual network suffix:**  001\
   **Stack name:**  mybob1221\
   **Stack owner:**  bob tayara\
   **Azure subscription:**  web\
   **Criticality:**  High\
   **Entity:**  US\
   **Cost center:**  99999
spec:
  type: service
  owner: user:guest
  lifecycle: experimental